// Generated by scripts/write-env.mjs during npm run build.
export const environment = {
  production: true,
  firebase: {
    "apiKey": "<FIREBASE_API_KEY>",
    "authDomain": "<PROJECT_ID>.firebaseapp.com",
    "projectId": "<PROJECT_ID>",
    "storageBucket": "<PROJECT_ID>.appspot.com",
    "messagingSenderId": "<MESSAGING_SENDER_ID>",
    "appId": "<APP_ID>"
},
};
