import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const outputPath = resolve('src/environments/environment.prod.ts');

const firebase = {
  apiKey: process.env.NG_APP_FIREBASE_API_KEY ?? '<FIREBASE_API_KEY>',
  authDomain: process.env.NG_APP_FIREBASE_AUTH_DOMAIN ?? '<PROJECT_ID>.firebaseapp.com',
  projectId: process.env.NG_APP_FIREBASE_PROJECT_ID ?? '<PROJECT_ID>',
  storageBucket: process.env.NG_APP_FIREBASE_STORAGE_BUCKET ?? '<PROJECT_ID>.appspot.com',
  messagingSenderId: process.env.NG_APP_FIREBASE_MESSAGING_SENDER_ID ?? '<MESSAGING_SENDER_ID>',
  appId: process.env.NG_APP_FIREBASE_APP_ID ?? '<APP_ID>',
};

const contents = `// Generated by scripts/write-env.mjs during npm run build.
export const environment = {
  production: true,
  firebase: ${JSON.stringify(firebase, null, 4)},
};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, contents);
